const actions = {
    GET_FEEDBACK: "GET_FEEDBACK",
    SET_FEEDBACK: "SET_FEEDBACK",
    CREATE_FEEDBACK: "CREATE_FEEDBACK",
    LOADING: "LOADING",
    DELETE_FEEDBACK: "DELETE_FEEDBACK",
    UPDATE_FEEDBACK: "UPDATE_FEEDBACK",
    FILTER_FEEDBACK: "FILTER_FEEDBACK"
}
export default actions