const jobApplyListActions = {
    GET_JOB_APPLY_LIST: "GET_JOB_APPLY_LIST",
    GET_JOB_APPLY_LIST_SUCCESS: "GET_JOB_APPLY_LIST_SUCCESS",
    GET_JOB_APPLY_LIST_FAILURE: "GET_JOB_APPLY_LIST_FAILURE",
    SET_JOB_APPLY_LIST_LOADER: "SET_JOB_APPLY_LIST_LOADER",
    RESET_JOB_APPLY_LIST_STATE: "RESET_JOB_APPLY_LIST_STATE"
  };
  
  export default jobApplyListActions;