const actions = {
  SET_SUBSCRIPTION_STATE: "SET_SUBSCRIPTION_STATE",
  GET_SUBSCRIPTION: "GET_SUBSCRIPTION",
  SET_SUBSCRIPTION_LODING: "SET_SUBSCRIPTION_LODING",
  DECREASE_RESUME_DOWNLOADING: "DECREASE_RESUME_DOWNLOADING",
  RESUME_COUNT_FINISH: "RESUME_COUNT_FINISH"
};
export default actions;
