const jobOpeningMatchesActions = {
    SET_JOB_MATCHES_STATE: 'SET_JOB_MATCHES_STATE',
    JOB_MATCHES_LOADER: 'JOB_MATCHES_LOADER',
    GET_JOB_OPENING_ROW: 'GET_JOB_OPENING_ROW',
    GET_JOB_OPENING_MATCH_CANDIDATE: 'GET_JOB_OPENING_MATCH_CANDIDATE',
}
export default jobOpeningMatchesActions