const actions = {
  GET_JOBOPENING: "GET_JOBOPENING",
  FIND_BY_ID_JOBOPENING: "FIND_BY_ID_JOBOPENING",
  SET_JOBOPENING: "SET_JOBOPENING",
  CREATE_JOBOPENING: "CREATE_JOBOPENING",
  LOADING: "LOADING",
  DELETE_JOBOPENING: "DELETE_JOBOPENING",
  UPDATE_JOBOPENING: "UPDATE_JOBOPENING",
  RESTART_JOBOPENING: "RESTART_JOBOPENING",
  FILTER_JOBOPENING: "FILTER_JOBOPENING",
};
export default actions;
