const actions = {
  GET_EDUCATIONS: "GET_EDUCATIONS",
  SET_EDUCATIONS: "SET_EDUCATIONS",
  CREATE_EDUCATION: "CREATE_EDUCATION",
  UPDATE_EDUCATION: "UPDATE_EDUCATION",
  DELETE_EDUCATION: "DELETE_EDUCATION",
  GET_COURSES: "GET_COURSES",
  SET_COURSES: "SET_COURSES",
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
};

export default actions;
