const actions = {
  GET_JOBSUBCAT: "GET_JOBSUBCAT",
  GET_ALL_JOBSUBCAT: "GET_ALL_JOBSUBCAT",
  SET_JOBSUBCAT: "SET_JOBSUBCAT",
  CREATE_JOBSUBCAT: "CREATE_JOBSUBCAT",
  DELETE_JOBSUBCAT: "DELETE_JOBSUBCAT",
  UPDATE_JOBSUBCAT: "UPDATE_JOBSUBCAT",
};
export default actions;
